### ISSUE TITLE
mongo_collection doesn't seem to be available

### ISSUE THREAD

**Issue by Babyjack** [drewrice2/GDAX_to_remote_MongoDB#2]
I get this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'mongo_collection'

**Comment by drewrice2** [comment]
make sure you're using my implementation, versus the GDAX implementation (from `pip install gdax`).

**Comment by drewrice2** [comment]
closing this issue. @Babyjack let me know if you're having trouble and i can reopen.

**Comment by Babyjack** [comment]
Great it worked thanks!
